### PR TITLE
Update to new os name

### PR DESCRIPTION
**Pull request by laurrentt**
OS X is so yesterday... get up-to-date son :trollface:

### CODE REVIEW

**Comment by joallard** [comment]
Thanks. Would you squash them together?

**Comment by laurrentt** [comment]
Why don't you use the "new" squash and merge button ? 
image

**Comment by joallard** [comment]
Simply because I hadn't seen it yet. But because you asked so politely, why wouldn't I oblige?

**Comment by laurrentt** [comment]
Sorry for being rude I knew I should have added a "😉" at the end. I could not use a Mac without this custom keyboard so I owe you much respect.  Merci encore !

**Comment by joallard** [comment]
Thanks, I appreciate. Same thing when I got onto ~~OS X~~ macOS a few years back. However I'm not the author of the layout, I just maintain and have the pleasure of dealing with contributions ;) Cheers

**Pull request merged**
